
%% 清理工作区
clear;
clc;
close all;

%% 用户配置
% -------------------------------------------------------------------------
% 输出文件名
output_filename = 'sawtooth_128x14.mif'; 

% DAC分辨率 (bit)
bit_depth = 14;

% 每个周期的采样点数 (MIF文件的深度)
num_points = 128; % 例如: 64, 128, 256, 512, 1024

% 波形类型: 'sine', 'square', 'triangle', 'sawtooth'
waveform_type = 'sawtooth';
% -------------------------------------------------------------------------


%% 参数计算
% 根据位宽计算DAC的最大值
max_val = 2^bit_depth - 1;

% 创建一个从0到num_points-1的索引向量
index = 0:(num_points - 1);

% 初始化数据向量
data = zeros(1, num_points);


%% 波形生成
fprintf('正在生成 %s 波形数据...\n', waveform_type);

switch lower(waveform_type)
    case 'sine'
        % 正弦波: 幅度从0到max_val
        amplitude = max_val / 2;
        offset = max_val / 2;
        data = amplitude * sin(2 * pi * index / num_points) + offset;
        
    case 'square'
        % 方波: 50%占空比
        half_point = floor(num_points / 2);
        data(1:half_point) = max_val;
        data(half_point+1:num_points) = 0;
        
    case 'triangle'
        % 三角波: 上升沿和下降沿对称
        half_point = floor(num_points / 2);
        % 上升沿 (从 0 到 max_val)
        up_ramp = linspace(0, max_val, half_point);
        % 下降沿 (从 max_val 回到 0)
        down_ramp = linspace(max_val, 0, num_points - half_point);
        data = [up_ramp, down_ramp];
        
    case 'sawtooth'
        % 锯齿波: 线性从0上升到max_val
        data = linspace(0, max_val, num_points);
        
    otherwise
        error('错误: 未知的波形类型 "%s"。请选择 ''sine'', ''square'', ''triangle'', or ''sawtooth''。', waveform_type);
end

% 将浮点数据四舍五入为整数
data_int = round(data);

% 确保数据在有效范围内 [0, max_val]
data_int(data_int > max_val) = max_val;
data_int(data_int < 0) = 0;


%% 写入MIF文件
fprintf('正在将数据写入到文件: %s\n', output_filename);

% 以写入模式打开文件
fileID = fopen(output_filename, 'w');
if fileID == -1
    error('无法创建或打开文件: %s', output_filename);
end

% 写入MIF文件头
fprintf(fileID, '-- MIF file generated by MATLAB\n');
fprintf(fileID, '-- Waveform: %s\n', waveform_type);
fprintf(fileID, '--\n');
fprintf(fileID, 'WIDTH = %d;\n', bit_depth);
fprintf(fileID, 'DEPTH = %d;\n', num_points);
fprintf(fileID, 'ADDRESS_RADIX = DEC;\n');
fprintf(fileID, 'DATA_RADIX = DEC;\n\n');
fprintf(fileID, 'CONTENT BEGIN\n');

% 写入数据内容
for i = 1:num_points
    % 格式: 地址 : 数据;
    fprintf(fileID, '\t%d : %d;\n', i - 1, data_int(i));
end

% 写入文件尾
fprintf(fileID, 'END;\n');

% 关闭文件
fclose(fileID);

fprintf('MIF文件 "%s" 已成功生成！\n', output_filename);


%% (可选) 绘制波形以供预览
figure;
plot(index, data_int, '-o');
title(['生成的波形预览: ' waveform_type]);
xlabel('采样点 (地址)');
ylabel(['DAC 数值 (0-' num2str(max_val) ')']);
grid on;
axis tight;